[package]
name = "pas"
version = "0.1.0"
authors = ["Sergey Reshetnikov <shaman@simmirra.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iso_country = "0.1.4"
# actix-web = "3"
